on:
  release:
    types: released
jobs:
  publish-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go run ./task/buildx
      - uses: jcbhmr/configure-executable-action@v1
      - uses: actions4git/add-commit-push@v1
      - uses: actions4gh/publish-action@v1
