name: Test action
on:
  push:
    branches: "main"
  pull_request:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: tree -a /opt/hostedtoolcache/go/
      # - id: main
      #   uses: ./
      # - shell: cat {0}
      #   run: ${{ toJSON(steps.main.outputs) }}
